"""Generate VLM captions for a small image subset and exercise the
caption→text→image retrieval path.

The bundled set is parsed without VLM by default; this script demonstrates
how to enable ``ENABLE_VLM=true`` on a curated subset (here: 10 Caltech-101
images spanning animals / food / plants / instruments / landmarks) and
verify the resulting captions flow into the text search path. The query
test at the bottom of the file takes 10 natural-language descriptions of
the captioned images and runs them through ``hybrid_search`` to confirm
the captions land in the right text chunks.

Each caption is ~1300 Chinese characters, generated by
``gemma4:latest`` (ollama, OpenAI-compatible) following the prompt
"可检索对象/文字/场景/用途/可回答问题". Each caption takes ~20 seconds
because gemma4 runs its reasoning pass before producing the answer.

Usage::

    export MM_ASSET_RAG_HOME=$HOME/.mm_asset_rag
    export VLM_BASE_URL=http://127.0.0.1:11434/v1
    export VLM_API_KEY=ollama
    export VLM_MODEL=gemma4:latest
    python scripts/import_vlm_captions.py
"""

from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

# Make the package importable when running from a checkout.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from mm_asset_rag.assets import load_assets  # noqa: E402
from mm_asset_rag.config import load_env  # noqa: E402

load_env()

from mm_asset_rag.backends.qdrant_backend import (  # noqa: E402
    _embed_bm25,
    get_qdrant_client,
    stable_point_id,
    text_collection,
)
from mm_asset_rag.embedders.text_embedder import EmbeddingProvider  # noqa: E402
from mm_asset_rag.parsers.image_parser import parse_image  # noqa: E402
from mm_asset_rag.paths import get_documents_jsonl  # noqa: E402

# 10 representative Caltech-101 images — one per high-confidence category.
# The same list is used in ``scripts/eval_extended.py`` as the
# ``vlm_caption`` ground truth, so changes here must mirror that.
TARGET_IDS: list[str] = [
    "caltech_airplanes_01",
    "caltech_dolphin_01",
    "caltech_panda_01",
    "caltech_pizza_01",
    "caltech_brain_01",
    "caltech_buddha_01",
    "caltech_sunflower_01",
    "caltech_lotus_01",
    "caltech_pagoda_01",
    "caltech_saxophone_01",
]

# Short natural-language descriptions used as the test query. Each is what
# a real user would type if they had the captioned image in mind.
EXPECTED_QUERIES: list[tuple[str, str]] = [
    ("海豚 海洋哺乳动物", "caltech_dolphin_01"),
    ("大熊猫 黑白", "caltech_panda_01"),
    ("比萨饼 食物", "caltech_pizza_01"),
    ("向日葵 黄色花卉", "caltech_sunflower_01"),
    ("宝塔 建筑", "caltech_pagoda_01"),
    ("萨克斯管 乐器", "caltech_saxophone_01"),
    ("佛像 雕塑", "caltech_buddha_01"),
    ("脑部 解剖", "caltech_brain_01"),
    ("飞机 航空器", "caltech_airplanes_01"),
    ("莲花 水生植物", "caltech_lotus_01"),
]


def generate_captions() -> int:
    """Run VLM on each target and append the resulting ParsedDocument to
    ``documents.jsonl``. Returns the number of captions written.
    """
    target = get_documents_jsonl()
    by_id = {a.asset_id: a for a in load_assets() if a.asset_id in TARGET_IDS}
    written = 0
    for asset_id in TARGET_IDS:
        a = by_id.get(asset_id)
        if a is None:
            print(f"  skip (not in manifest): {asset_id}")
            continue
        t0 = time.perf_counter()
        try:
            docs = parse_image(a, enable_ocr=False, enable_vlm=True)
        except Exception as exc:
            print(f"  {asset_id}: ERROR {type(exc).__name__}: {exc}")
            continue
        elapsed = time.perf_counter() - t0
        with target.open("a", encoding="utf-8") as f:
            for d in docs:
                f.write(json.dumps(d.to_json(), ensure_ascii=False) + "\n")
                written += 1
        print(f"  {asset_id} ({elapsed:.1f}s, {len(docs)} doc)")
    return written


def upsert_to_text_index(written: int) -> int:
    """Incrementally upsert the VLM-captioned chunks to the text collection.

    ``mmrag reindex --text-only`` would re-embed every chunk; this direct
    upsert is faster because it only touches the new ones. The point id
    is deterministic so re-runs are no-ops.
    """
    target = get_documents_jsonl()
    embedder = EmbeddingProvider()
    client = get_qdrant_client()
    coll = text_collection(2560)  # qwen3-embedding:4b is 2560d

    from qdrant_client import models

    upserted = 0
    with target.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            d = json.loads(line)
            md = d.get("metadata", {})
            if md.get("source_type") != "image" or md.get("parser") != "image-ocr-vlm":
                continue
            text = d["text"]
            asset_id = md.get("asset_id", "")
            if not asset_id.startswith("caltech_"):
                continue
            if asset_id not in TARGET_IDS:
                continue
            point_id = stable_point_id(f"text:{asset_id}:vlm:0")
            dense_vec = embedder.embed(text)
            bm25_vec = _embed_bm25([text])[0]
            payload = {**md, "text": text, "doc_key": f"vlm:{asset_id}"}
            client.upsert(
                collection_name=coll,
                points=[
                    models.PointStruct(
                        id=point_id,
                        vector={"dense": dense_vec, "bm25": bm25_vec},
                        payload=payload,
                    )
                ],
                wait=True,
            )
            upserted += 1
    return upserted


def test_caption_retrieval() -> dict:
    """Hit-rate of natural-language caption queries against hybrid_search."""
    from mm_asset_rag.retrieval import hybrid_search

    hits = 0
    detail: list[dict] = []
    for query, expected in EXPECTED_QUERIES:
        results = hybrid_search(query, top_k=5)
        actual = [h.asset_id for h in results]
        hit = expected in actual
        hits += int(hit)
        detail.append(
            {
                "query": query,
                "expected": expected,
                "actual_top3": actual[:3],
                "hit_at_5": hit,
            }
        )
    return {
        "n": len(EXPECTED_QUERIES),
        "hit_rate_at_5": hits / len(EXPECTED_QUERIES),
        "details": detail,
    }


def main() -> None:
    print(f"VLM_BASE_URL={os.environ.get('VLM_BASE_URL')!r}")
    print(f"VLM_MODEL={os.environ.get('VLM_MODEL')!r}")

    if not all(os.environ.get(k) for k in ("VLM_BASE_URL", "VLM_API_KEY", "VLM_MODEL")):
        print("VLM is not configured. Set VLM_BASE_URL / VLM_API_KEY / VLM_MODEL in .env")
        sys.exit(1)

    print("\n[1/3] generating VLM captions (gemma4 with thinking: ~20s each)...")
    written = generate_captions()
    print(f"  wrote {written} caption documents")

    print("\n[2/3] upserting caption chunks to Qdrant text collection...")
    upserted = upsert_to_text_index(written)
    print(f"  upserted {upserted} caption chunks")

    print("\n[3/3] testing caption→text→image retrieval...")
    report = test_caption_retrieval()
    print(
        f"  hit_rate@5 = {report['hit_rate_at_5']:.1%} ({int(report['hit_rate_at_5'] * report['n'])}/{report['n']})"
    )
    for d in report["details"]:
        mark = "✓" if d["hit_at_5"] else "✗"
        print(f"    {mark} q={d['query']!r:30s}  actual[:3]={d['actual_top3']}")


if __name__ == "__main__":
    main()
